const mongoose = require('mongoose');

const TransactionSchema = new mongoose.Schema({
    receiptNo:     { type: String, required: true, unique: true },
    orderNo:       { type: String, default: '' },
    orderStatus:   { type: String, enum: ['pending', 'preparing', 'ready', 'completed', 'cancelled'], default: 'pending' },
    statusUpdatedAt: { type: Date, default: Date.now },
    cancelledAt:   { type: Date, default: null },
    cancelledBy:   { type: String, default: '' },
    cancelReason:  { type: String, default: '' },
    cancellationRefundId: { type: mongoose.Schema.Types.ObjectId, ref: 'Refund', default: null },
    cancelledItems: [{
        originalIndex: Number,
        productId: { type: mongoose.Schema.Types.ObjectId, ref: 'Product' },
        name: String,
        quantity: Number,
        price: Number,
        subtotal: Number,
        reason: String,
        cancelledBy: String,
        cancelledByEmail: String,
        refundId: { type: mongoose.Schema.Types.ObjectId, ref: 'Refund' },
        cancelledAt: { type: Date, default: Date.now },
    }],
    cashier:       { type: String, required: true },
    cashierEmail:  { type: String, default: '' },
    customerType:  { type: String, enum: ['customer', 'elite', 'pagibig', 'pwd_senior', 'custom_discount'], default: 'customer' },
    serviceType:   { type: String, enum: ['Dine In', 'Dine Out'], default: 'Dine In' },
    eliteMember:   { name: String, idNumber: String },
    discountInfo:  {
        name:       String,
        percentage: Number,
        code:       String,
    },
    items: [{
        productId:       { type: mongoose.Schema.Types.ObjectId, ref: 'Product' },
        name:            String,
        category:        String,
        size:            String,
        selectedVariant: String,
        upgrades: [{
            name:        String,
            price:       Number,
        }],
        price:           Number,
        quantity:        Number,
        subtotal:        Number,
        discountEligibleQuantity: { type: Number, default: 0 },
    }],
    subtotal:       { type: Number, required: true },
    tax:            { type: Number, default: 0 },
    discount:       { type: Number, default: 0 },
    total:          { type: Number, required: true },
    paymentMethod:  { type: String, enum: ['Cash', 'GCash', 'Cancelled'], required: true },
    amountTendered: { type: Number, default: 0 },
    change:         { type: Number, default: 0 },
    gcashReference: { type: String, default: null },
    gcashProofImage:{ type: String, default: null },
}, {
    collection: 'transactions',
    timestamps: true,
});

module.exports = mongoose.model('Transaction', TransactionSchema);
